# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      
      - name: Deploy to Heroku
        env:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "arcane-cove-04720"
          heroku_email: "a0987642936@gmail.com"  
        run: cd server && git remote add heroku https://git.heroku.com/arcane-cove-04720.git && git push heroku master
